# Generated by Django 3.1.1 on 2020-10-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Cliente',
                'required_db_vendor': 'mysql',
            },
        ),
    ]
