# Generated by Django 3.1.1 on 2020-11-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_remove_usuario_usuario_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
