# Generated by Django 3.1.1 on 2020-10-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_auto_20201027_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contrasenia',
            field=models.CharField(max_length=40, verbose_name='Constraseña'),
        ),
    ]
