# Generated by Django 3.1.1 on 2020-10-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_auto_20201027_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contrasenia',
            field=models.CharField(max_length=400, verbose_name='Constraseña'),
        ),
    ]
