# Generated by Django 3.1.1 on 2020-10-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20201020_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['precio']},
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(auto_now=True, verbose_name='Fecha del pedido')),
                ('entregado', models.BooleanField(default=False)),
                ('id_Producto', models.ManyToManyField(to='productos.Producto')),
            ],
            options={
                'db_table': 'Pedido',
                'ordering': ['fecha_pedido'],
                'required_db_vendor': 'mysql',
            },
        ),
    ]
