# Generated by Django 3.1.1 on 2020-10-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20201021_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='numero_pedido',
            field=models.IntegerField(null=True),
        ),
    ]
