# Generated by Django 3.1.1 on 2020-10-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_pedidos_numero_pedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Pedido',
        ),
    ]
