# Generated by Django 3.1.1 on 2020-11-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20201027_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='', max_length=100, verbose_name='Ruta de la imagen'),
            preserve_default=False,
        ),
    ]
