# Generated by Django 3.1.1 on 2020-11-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_tipo_prenda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
